
language: python

matrix:
    include:
     - sudo: required
       services:
         - docker
       python: "3.6"
       env: CIBW_BEFORE_BUILD="yum -y install zlib-devel && pip install Cython && pip install numpy==1.13" PIP=pip CIBW_SKIP="*i686 cp37*"
       install:
         - $PIP install cibuildwheel==0.9.3
       script:
         - cibuildwheel --output-dir wheelhouse
     - sudo: required
       services:
         - docker
       python: "3.6"
       env: CIBW_BEFORE_BUILD="yum -y install zlib-devel && pip install Cython && pip install numpy==1.13" PIP=pip CIBW_SKIP="*x86_64 cp37*"
       install:
         - $PIP install cibuildwheel==0.9.3
       script:
         - cibuildwheel --output-dir wheelhouse
     - sudo: required
       services:
         - docker
       python: "3.6"
       env: CIBW_BEFORE_BUILD="yum -y install zlib-devel && pip install Cython && pip install numpy==1.14" PIP=pip CIBW_SKIP="cp27* cp34* cp35* cp36*"
       install:
         - $PIP install cibuildwheel==0.9.3
       script:
         - cibuildwheel --output-dir wheelhouse

     - os: osx
       before_install: brew update;brew cask uninstall oclint; brew install gcc
       language: generic
       env: CIBW_BEFORE_BUILD="pip install Cython && pip install numpy==1.13" PIP=pip2
       install:
         - $PIP install cibuildwheel==0.9.3;
       script:
         - cibuildwheel --output-dir wheelhouse

env:
  global:
    - CIBW_TEST_COMMAND="bash {project}/test/run_test.sh"
    - CIBW_TEST_REQUIRES=pytest
