
language: python


install:
 - $PIP install --upgrade cibuildwheel==1.0;

script:
 - cibuildwheel --output-dir wheelhouse
 - if [[ $TRAVIS_TAG ]]; then
     echo $TRAVIS_TAG;
     brew update;
     brew install python2;
     brew link --overwrite python2;
     sudo $PIP install twine;
     twine upload --skip-existing wheelhouse/*.whl;
   fi

jobs:
    include:
     - services:
         - docker
       python: "3.6"
       env: CIBW_BEFORE_BUILD="yum -y install zlib-devel && pip install Cython && pip install numpy==1.16 && pip install starlink-pyast" PIP=pip CIBW_BUILD="cp27-*x86_64"

     - services:
         - docker
       python: "3.6"
       env: CIBW_BEFORE_BUILD="yum -y install zlib-devel && pip install Cython && pip install numpy==1.16 && pip install starlink-pyast" PIP=pip CIBW_BUILD="cp27-*i686"

     - services:
         - docker
       python: "3.6"
       env: CIBW_BEFORE_BUILD="yum -y install zlib-devel && pip install Cython && pip install numpy==1.16 && pip install starlink-pyast" PIP=pip CIBW_BUILD="cp35-*"

     - services:
         - docker
       python: "3.6"
       env: CIBW_BEFORE_BUILD="yum -y install zlib-devel && pip install Cython && pip install numpy==1.16 && pip install starlink-pyast" PIP=pip CIBW_BUILD="*cp36-*"

     - services:
         - docker
       python: "3.6"
       env: CIBW_BEFORE_BUILD="yum -y install zlib-devel && pip install Cython && pip install numpy==1.16 && pip install starlink-pyast" PIP=pip CIBW_BUILD="cp37-*"



     - os: osx
       before_install: brew update;
       language: generic
       env: CIBW_BEFORE_BUILD="pip install Cython && pip install numpy==1.16 && pip install starlink-pyast" PIP=pip2 CIBW_BUILD="cp27*"

     - os: osx
       before_install: brew update;
       language: generic
       env: CIBW_BEFORE_BUILD="pip install Cython && pip install numpy==1.16 && pip install starlink-pyast" PIP=pip2 CIBW_BUILD="cp35*"

     - os: osx
       before_install: brew update;
       language: generic
       env: CIBW_BEFORE_BUILD="pip install Cython && pip install numpy==1.16 && pip install starlink-pyast" PIP=pip2 CIBW_BUILD="cp36*"

     - os: osx
       before_install: brew update;
       language: generic
       env: CIBW_BEFORE_BUILD="pip install Cython && pip install numpy==1.16 && pip install starlink-pyast" PIP=pip2 CIBW_BUILD="cp37*"

env:
  global:
    - CIBW_TEST_COMMAND="bash {project}/test/run_test.sh"
    - CIBW_TEST_REQUIRES=pytest
    - TWINE_USERNAME=sgraves
    - CIBW_BUILD_VERBOSITY=1
