language: python

python:
 - "3.6"
 - "3.5"
 - "2.7"

os:
 - linux


before_install:
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install gfortran; fi



install:
 - pip install Cython
 - pip install .

script:  pytest