
language: python

matrix:
    include:
     - sudo: required
       services:
         - docker
       python: "3.6"
       env: CIBW_BEFORE_BUILD="yum -y install zlib-devel && pip install Cython && pip install numpy" PIP=pip
       install:
         - $PIP install cibuildwheel==0.9.3
       script:
         - cibuildwheel --output-dir wheelhouse
     - os: osx
       before_install: brew update;brew cask uninstall oclint; brew install gcc
       language: generic
       env: CIBW_BEFORE_BUILD="pip install Cython && pip install numpy" PIP=pip2
       install:
         - $PIP install cibuildwheel==0.9.3;
       script:
         - cibuildwheel --output-dir wheelhouse

env:
  global:
    - CIBW_TEST_COMMAND="pytest -v {project}/test; export HDS_VERSION=5; pytest -v {project}/test"
    - CIBW_TEST_REQUIRES=pytest
