
language: python

install:
 - $PIP install --upgrade cibuildwheel==0.9.3;

script:
 - cibuildwheel --output-dir wheelhouse
 - if [[ $TRAVIS_TAG ]]; then
     echo $TRAVIS_TAG;
     brew update;
     brew install python2;
     brew link --overwrite python2;
     sudo $PIP install twine;
     twine upload --skip-existing wheelhouse/*.whl;
   fi

matrix:
    include:
     - sudo: required
       services:
         - docker
       python: "3.6"
       env: CIBW_BEFORE_BUILD="yum -y install zlib-devel && pip install Cython && pip install numpy==1.15 && pip install starlink-pyast" PIP=pip CIBW_SKIP="*i686 cp37*"

     - sudo: required
       services:
         - docker
       python: "3.6"
       env: CIBW_BEFORE_BUILD="yum -y install zlib-devel && pip install Cython && pip install numpy==1.15 && pip install starlink-pyast" PIP=pip CIBW_SKIP="*x86_64 cp37*"

     - sudo: required
       services:
         - docker
       python: "3.6"
       env: CIBW_BEFORE_BUILD="yum -y install zlib-devel && pip install Cython && pip install numpy==1.16 && pip install starlink-pyast" PIP=pip CIBW_SKIP="cp27* cp34* cp35* cp36*"

     - os: osx
       before_install: brew update;brew cask uninstall oclint; brew install gcc
       language: generic
       env: CIBW_BEFORE_BUILD="pip install Cython && pip install numpy==1.15 && pip install starlink-pyast" PIP=pip2 CIBW_SKIP="cp37*"

     - os: osx
       before_install: brew update;brew cask uninstall oclint; brew install gcc;
       language: generic
       env: CIBW_BEFORE_BUILD="pip install Cython && pip install numpy==1.16 && pip install starlink-pyast" PIP=pip2 CIBW_SKIP="cp27 cp34* cp35* cp36*"

env:
  global:
    - CIBW_TEST_COMMAND="bash {project}/test/run_test.sh"
    - CIBW_TEST_REQUIRES=pytest
    - TWINE_USERNAME=sgraves
